### PR TITLE
October 2021 Update

### PR DESCRIPTION
**Pull request by codingbandit**
Please note: the Spark pool was not updated to version 3.1 due to the integration with Azure Machine Learning not being able to support it yet.

### CODE REVIEW

**Comment by thevinnie** [comment]
In the Before the HOL I ran into the following:

1. In the prep script, AzureStorageContext should be AzStorageContext

Screen Shot 2021-11-12 at 10 25 33 AM

2. The following tables were not created and returned an error in the validation portion of the setup.
 Table ASAMCWMLModelExt not found
 Table ASAMCWMLModel not found
 External table ASAMCWMLModelExt not found
Note: Validation was “successful” when the objects weren’t present

3. I was able to run this from my local powershell interface (MacOS using pwsh) by installing the Az and SqlServer libraries and azcopy utility.  Could be something to consider in the future or as a subnote for user who want to use their local CLI instead of cloud shell.

**Comment by codingbandit** [comment]
@thevinnie - I wasn't able to reproduce the issue. Were you running the setup in the Cloud shell? We have the instructions use the cloud shell as supporting various personal workstation setups yields a lot of unpredictable experiences. New-AzureStorageContext and New--AzureStorageContainerSASToken is still valid syntax and runs as expected in the cloud shell.

image

**Comment by thevinnie** [comment]
> @thevinnie - I wasn't able to reproduce the issue. Were you running the setup in the Cloud shell? We have the instructions use the cloud shell as supporting various personal workstation setups yields a lot of unpredictable experiences. New-AzureStorageContext and New--AzureStorageContainerSASToken is still valid syntax and runs as expected in the cloud shell.
> 
> image

I was using a local CLI and not Cloud Shell, so I understand that it is a variation from the directions, but I'm calling it out here because it's the only dependency I see on modules not included in the Az library.  It's worth adjusting so future changes don't break that part of the setup.

**Comment by thevinnie** [comment]
The only other comment I have is not related to a specific change in the WDS trainer guide, but instead something which I believe is missing.  In order to design a suitable solution for a customer, we need to understand their technical requirements AND existing capabilities.  We need our field folks to be empathetic to the changes a customer may need to go through in order to adopt a proposed solution.  It's a minor tweak but a critical sentiment.

In the screenshot, I would recommend changing "Current customer infrastructure and architecture" to something like "Customer's current infrastructure, architecture, and capabilities".  That would also allow for including a discussion of how to educate the "doers" in order to bridge the skills gap should the customer want to use a net-new service.  And, say, use something like a hands-on-lab to help facilitate training and onboarding.  =]


Screen Shot 2021-11-12 at 2 00 19 PM

**Comment by codingbandit** [comment]
Thank you @thevinnie ! I have made the changes. @DawnmarieDesJardins - this is ready for QC, I've already made the changes for the renaming of the branch.

**Pull request merged**
